ToC on every page
ChalmersGU-data-structure-courses/dsabook pull request #9
Opened 2024-04-22 12:04 UTC by Wincent01

Fixes: #5 

This pull request seeks to display the ToC on every page. Postprocessing is used to replace the old navigation with a ToC that is displayed on the side. JS is used for some reactive behavior, like scrolling to the current page in the ToC.

Additional accommodations for small screens is needed.

See below for how it looks on the side.

![image](https://github.com/ChalmersGU-data-structure-courses/dsabook/assets/18661153/ff572d0d-77cd-4b0c-8bbb-5ff334b0c6c0)

2024-05-14 09:09 UTC, heatherleaf requested changes
Looking good! 

But I think that you can simplify some steps - see my specific comments, and in particular the one to `make.sh`

2024-05-14 09:09 UTC, heatherleaf commented on postprocess.py
Also, I do prefer the type hints. The union type `a|b` was added in Python 3.10, so perhaps it's time to upgrade...:)

2024-05-14 09:09 UTC, heatherleaf commented on make.sh
Pandoc can add the toc to all files automatically: https://github.com/jgm/pandoc/issues/8561#issuecomment-1397805213

(But instead of giving `-Vtoc` as cmd-line argument, I prefer to use `variable:` in `pandoc-defaults.yaml`: https://pandoc.org/MANUAL.html#general-writer-options-1)

2024-05-20 12:31 UTC, Wincent01 commented
Closing. See #12

2024-05-20 12:31 UTC, closed without merging